### PR TITLE
Bump form-data to fix regex denial of service

### LINKED ISSUE #30: Regular Expression Denial of Service through transitive dependency on mime
`nsp check` reports a regex DOS vulnerability via `form-data` -> `mime`. `form-data` should be updated to fix this.

image

See https://nodesecurity.io/advisories/535 for more info.

### PR DESCRIPTION
**Pull request by gabegorelick**
Fixes #30

### CODE REVIEW

**Comment by gabegorelick** [comment]
Build is failing on `iojs`. Is that still a supported platform?

**Comment by vigandhi** [comment]
@renderf0x any way we can get this in? Would be nice to fix the issue to keep everyone's `npm audit` clean

**Comment by renderf0x** [comment]
Heya there @vigandhi -
I no longer have permissions on this package, but you may want to ping @alexmac05 or @nathanbuchar to see if we can get some movement on this.

**Comment by vigandhi** [comment]
@nathanbuchar @alexmac05  bump ^ any thoughts on this?

**Comment by gabegorelick** [comment]
Rebased to fix build. Should be ready for merging.

**Comment by nathanbuchar** [comment]
Thanks @gabegorelick :)

**Comment by theoephraim** [comment]
thanks for merging this guys - can you please republish to npm?

**Comment by nathanbuchar** [comment]
@theoephraim whoops, my bad! I'll do that now.

**Comment by nathanbuchar** [comment]
Done

**Pull request merged**
